### ISSUE TITLE
Issue with feedstock packaging an old version

### ISSUE THREAD

**Issue by ResidentMario** [conda-forge/kealib-feedstock#15]
In updating the feedstock for `geoplot` ([here](https://github.com/conda-forge/geoplot-feedstock)), the Travis CI test on Python 3.6 ran into a C-level dynamic linkage failure. [Failure details are here](https://travis-ci.org/conda-forge/geoplot-feedstock/jobs/288094247); here's the except:

```
import: 'geoplot'
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/geoplot_1508035084157/test_tmp/run_test.py", line 2, in <module>
    import geoplot
  File "/Users/travis/miniconda3/conda-bld/geoplot_1508035084157/_t_env/lib/python3.6/site-packages/geoplot/__init__.py", line 1, in <module>
    from .geoplot import (pointplot, polyplot, choropleth, aggplot, cartogram, kdeplot, sankey)
  File "/Users/travis/miniconda3/conda-bld/geoplot_1508035084157/_t_env/lib/python3.6/site-packages/geoplot/geoplot.py", line 5, in <module>
    import geopandas as gpd
  File "/Users/travis/miniconda3/conda-bld/geoplot_1508035084157/_t_env/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/Users/travis/miniconda3/conda-bld/geoplot_1508035084157/_t_env/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/Users/travis/miniconda3/conda-bld/geoplot_1508035084157/_t_env/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/travis/miniconda3/conda-bld/geoplot_1508035084157/_t_env/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/travis/miniconda3/conda-bld/geoplot_1508035084157/_t_env/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libkea.1.4.7.dylib
  Referenced from: /Users/travis/miniconda3/conda-bld/geoplot_1508035084157/_t_env/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 1.4.7 or later, but libkea.1.4.7.dylib provides version 1.4.0
```

To debug this, to start with, why is a library declared to be `1.4.7` serving a `1.4.0`?

An older recipe for this library which passed in September is now failing as well, so it had to have been due to the changes in the three commits in October.

**Comment by gillins** [comment]
@ResidentMario this error was fixed by rebuilding `libgdal` against the new `kealib`. @ocefpaf did this for gdal 2.2.2 (https://github.com/conda-forge/libgdal-feedstock/pull/13) and 2.1.4 (https://github.com/conda-forge/libgdal-feedstock/pull/12). I see `geoplot` is pulling in `gdal` 2.1.3 which hasn't been rebuilt...

@ocefpaf I think `gdal` needs to be rebuilt on the 2.1.x branch. I know you did `libgdal`, but Python packages will still be pulling in `gdal` (for 2.1.* they will be getting 2.1.3). Do you agree?

**Comment by ResidentMario** [comment]
Sounds like you've got a handle on the shape of it. I've not dealt with packaging these C libraries myself, so I am of limited help.

The last time I ran into something like this, I'd caught ocefpaf midway through changing pins. This time we need to rebuild something older than expected. A different flavor for every month...

**Comment by gillins** [comment]
OK ignore my comment about `gdal` needing to be rebuilt. I now see that `gdal 2.1.4` exists and should be selected (and would probably work given that `libgdal 2.1.4` has been rebuilt - I'm using this elsewhere with no problems). However, something is causing `gdal 2.1.3` to be selected (see https://travis-ci.org/conda-forge/geoplot-feedstock/jobs/288094247#L318), but I can't see what.... Any ideas?

**Comment by ocefpaf** [comment]
The conda solver does things no one understands :-(

We can pull libgdal 2.1.3 (but not for Windows b/c we don't have 2.1.4
there). However, nothing will stop conda from pulling it from defaults.
Channel preference is thrown away by conda sometimes.

**Comment by ResidentMario** [comment]
Dropping `2.1.3` on OSX and Linux would work me since the library I'm concerned about doesn't work on Windows anyway (at least, it didn't last time I tried it).

Sorry to hear that. =/
