### ISSUE TITLE
kealib 1.4.9 only works with hdf5 >= 1.10.2 when using libgdal

### ISSUE THREAD

**Issue by snowman2** [conda-forge/kealib-feedstock#21]
Issue:

When using kealib 1.4.9 and hdf5 <= 1.10.2, linking errors occur.

See:
- https://github.com/conda-forge/rasterio-feedstock/issues/66
- https://github.com/conda-forge/libgdal-feedstock/issues/50

**Comment by gillins** [comment]
`conda` shouldn't let you do this with the current pinning - I'll see if @ocefpaf has any thoughts.

Newer `hdf5` packages are built with C++11 mode switched on for the C++ bindings (which `kealib` uses) meaning there is incompatibility between these and earlier versions. I've only bothered building `kealib` 1.4.9 in C++11 mode (for `hdf5` 1.10.2) and I can't see why you would want older `hdf5` with the latest `kealib` ([changes](https://bitbucket.org/chchrsc/kealib/src/default/Changes.txt) are mainly packaging).

**Comment by snowman2** [comment]
Thanks for the clarification. Maybe pinning hdf5>=1.10.2 in the meta.yml would fix the problem then?

**Comment by ocefpaf** [comment]
> Thanks for the clarification. Maybe pinning hdf5>=1.10.2 in the meta.yml would fix the problem then?

It should've have been pinned by the yaml configuration file but I could not find it, probably a bad re-rendering. I'll send a PR to fix this soon and remove the current builds.
