### ISSUE TITLE
Wrong library name in Windows build in kea-config.bat

### ISSUE THREAD

**Issue by zklaus** [conda-forge/kealib-feedstock#43]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Not sure what changed, but in the Windows build, from [1.4.13](https://anaconda.org/conda-forge/kealib/1.4.13/download/win-64/kealib-1.4.13-h3b59ab9_1.tar.bz2) to [1.4.14](https://anaconda.org/conda-forge/kealib/1.4.14/download/win-64/kealib-1.4.14-ha3510f1_0.tar.bz2) the name of the library in the `kea-config.bat` changed from `libkea.lib` to `kea.lib`. However, the actual filename remained unchanged at `libkea.lib`.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by gillins** [comment]
@zklaus I think this is fixed in the most recent build via #44. Let me know if this helps.

I'll try and get this addressed upstream before the next release.

**Comment by zklaus** [comment]
Thanks, @gillins. Will give it a try!
